apiVersion: v1
kind: ConfigMap
metadata:
  name: discord-sky-config
  namespace: discord-sky
data:
  DOTNET_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  Bot__Status: "SnooPING AS usual"
  Bot__AllowedChannelNames: ""
  Bot__CommandPrefix: "!sky"
  Bot__HistoryMessageLimit: "20"
  Bot__MemoryDataPath: "/app/data/user_memories"
  Chaos__MaxPromptsPerHour: "20"
