apiVersion: v1
kind: ConfigMap
metadata:
  name: discord-sky-config
  namespace: discord-sky
data:
  DOTNET_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  Bot__Status: "SnooPING AS usual"
  Bot__CommandPrefix: "!sky"
  Bot__HistoryMessageLimit: "20"
  Bot__MemoryDataPath: "/app/data/user_memories"
  Bot__EnableUserMemory: "true"
  Bot__MaxMemoriesPerUser: "20"
  Bot__MemoryExtractionRate: "1.0"
  Bot__ConversationWindowTimeout: "00:03:00"
  Bot__MaxWindowMessages: "30"
  Bot__MaxWindowDuration: "00:30:00"
  Bot__MaxMemoriesPerExtraction: "15"
  Bot__EnableMemoryConsolidation: "true"
  Bot__ConsolidationTargetPercent: "0.75"
  Chaos__MaxPromptsPerHour: "20"
