apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discord-sky-memory
  namespace: discord-sky
  labels:
    app: discord-sky-bot
spec:
  storageClassName: azurefile
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
